version: '3.4'
services:
  db:
    volumes:
      - ./settings:/home/settings
    ports:
      - ${DB_PORT}:5432

  osmupdate:
    volumes:
      - ./settings:/home/settings

  pbfupdate:
    volumes:
      - ./settings:/home/settings
